name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SECR }}
          SSH_RSA_KEY: ${{ secrets.SECR_RSA }}
        run: |
          sudo apt-get install expect
          echo -e 'spawn ssh eddiezane@test-srv.itzero.ru "touch OK444.txt"\nexpect "yes/no/"\nsend "yes\\n"\nexpect "password:"\nsend "8403120\\n"\ninteract' > ssh7.sh
          chmod +x ssh7.sh
          /usr/bin/expect -f ./ssh7.sh
          #cat ssh7.sh
          ls -la
          #mkdir ~/.ssh
          ls ~/.ssh
          #echo $SSH_PRIVATE_KEY > ~/.ssh/id_rsa.pub
          #echo $SSH_RSA_KEY > ~/.ssh/id_rsa
          #echo $SSH_PRIVATE_KEY
          #ssh -tt eddiezane@test-srv.itzero.ru
          #cat log.txt
          #sudo apt-get install mc -y
          ls
          #sudo ping -c 2 8.8.8.8
          
