name: Command via SSH

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ls -a via OPEN SSH Private Key
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: ls -a
          host: test-srv.itzero.ru
          username: eddiezane
          password: ${{ secrets.PAS }}
        
        env:
          CI: true
